on:
    push:
        paths:
            - "**.php"
            - "**.yml"
        branches:
            - main
    pull_request:
        paths:
            - "**.php"
            - "**.yml"

name: "Tests"

jobs:
    run:
        name: "Tests on PHP ${{ matrix.php-versions }} / ${{ matrix.operating-system }}"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ["8.1", "8.2", "8.3", "8.4"]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v5

            - name: Install Nix
              uses: cachix/install-nix-action@v31

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: gd,mbstring,pcov
                  tools: cs2pr

            - name: Install dependencies
              uses: ramsey/composer-install@v3

            - name: Run Grumphp
              run: vendor/bin/grumphp run
